"""initial schema

Revision ID: cbadf2ae5fb7
Revises: 
Create Date: 2026-06-17 20:26:58.718073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbadf2ae5fb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_course_code_key'), 'courses', type_='unique')
    op.drop_constraint(op.f('courses_department_id_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'department_id')
    op.drop_column('courses', 'credits')
    op.drop_column('courses', 'max_seats')
    op.drop_column('courses', 'course_code')
    op.add_column('departments', sa.Column('department_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('departments_dept_name_key'), 'departments', type_='unique')
    op.drop_column('departments', 'head_of_dept')
    op.drop_column('departments', 'budget')
    op.drop_column('departments', 'dept_name')
    op.alter_column('enrollments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('enrollments', 'grade')
    op.drop_column('enrollments', 'enrollment_date')
    op.add_column('professors', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('professors_email_key'), 'professors', type_='unique')
    op.drop_column('professors', 'prof_name')
    op.drop_column('professors', 'email')
    op.drop_column('professors', 'salary')
    op.add_column('students', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('students_email_key'), 'students', type_='unique')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'email')
    op.drop_column('students', 'enrollment_year')
    op.drop_column('students', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('enrollment_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('students_email_key'), 'students', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'name')
    op.add_column('professors', sa.Column('salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('professors', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('professors', sa.Column('prof_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('professors_email_key'), 'professors', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('professors', 'name')
    op.add_column('enrollments', sa.Column('enrollment_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('enrollments', sa.Column('grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('departments', sa.Column('dept_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('departments', sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('head_of_dept', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('departments_dept_name_key'), 'departments', ['dept_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('departments', 'department_name')
    op.add_column('courses', sa.Column('course_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('max_seats', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('courses_department_id_fkey'), 'courses', 'departments', ['department_id'], ['department_id'])
    op.create_unique_constraint(op.f('courses_course_code_key'), 'courses', ['course_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
